// <auto-generated />
using System;
using AutoFac_NetCoreMVC.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AutoFac_NetCoreMVC.Migrations
{
    [DbContext(typeof(RaeClassContext))]
    [Migration("20181201160038_raeclass3")]
    partial class raeclass3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("AutoFac_NetCoreMVC.Models.LogRequest", b =>
                {
                    b.Property<int>("FId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FDetails");

                    b.Property<string>("FIPAddress");

                    b.Property<string>("FMessage");

                    b.Property<string>("FName");

                    b.Property<string>("FParameters");

                    b.Property<DateTime>("FRequestTime");

                    b.Property<string>("FRequestType");

                    b.Property<string>("FRequestUrl");

                    b.Property<string>("FRequestUser");

                    b.HasKey("FId");

                    b.ToTable("LogRequest","dbo");
                });

            modelBuilder.Entity("AutoFac_NetCoreMVC.Models.ReadContent", b =>
                {
                    b.Property<int>("FId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("FCreateTime");

                    b.Property<string>("FJsonData");

                    b.Property<string>("FLevel");

                    b.Property<DateTime>("FModifyTime");

                    b.Property<string>("FName");

                    b.Property<string>("FNumber");

                    b.HasKey("FId");

                    b.ToTable("ReadContent","dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
