// <auto-generated />
using System;
using AutoFac_NetCoreMVC.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AutoFac_NetCoreMVC.Migrations
{
    [DbContext(typeof(RaeClassContext))]
    partial class RaeClassContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("AutoFac_NetCoreMVC.Models.ReadContent", b =>
                {
                    b.Property<int>("FId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("FCreateTime");

                    b.Property<string>("FJsonData");

                    b.Property<string>("FLevel");

                    b.Property<DateTime>("FModifyTime");

                    b.Property<string>("FName");

                    b.Property<string>("FNumber");

                    b.Property<int>("Id");

                    b.HasKey("FId");

                    b.ToTable("ReadContent","dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
